# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_uber_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Add seeds configuration
seeds:
  my_uber_project:
    uber_eats:
      enabled: true
      materialized_as: table
    uber_ride:
      enabled: true
      materialized_as: table

# Update models configuration
models:
  olap:
    staging:
      staging:
        +tags:
        - "staging"
      intermediate:
        +tags:
        - "intermediate"
      marts:
        +tags:
        - "marts"        
